-- MySQL Script generated by MySQL Workbench
-- Thu Jan 23 14:27:33 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cofinance
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cofinance` ;

-- -----------------------------------------------------
-- Schema cofinance
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cofinance` DEFAULT CHARACTER SET utf8 ;
USE `cofinance` ;

-- -----------------------------------------------------
-- Table `cofinance`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cofinance`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `cofinance`.`Usuario` (
  `cedula` VARCHAR(10) NOT NULL,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `fechaNaciemiento` DATE NOT NULL,
  `edad` SMALLINT NULL,
  `correoElectronico` VARCHAR(50) NOT NULL,
  `contraseña` VARCHAR(50) NOT NULL,
  `estadoVerificacion` ENUM('Pendiente', 'Verificado', 'Rechazado') NOT NULL DEFAULT 'Pendiente',
  `fotografia` MEDIUMBLOB NULL,
  `fechaCreacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `estado` ENUM('Activo', 'Inactivo') NOT NULL DEFAULT 'Activo',
  PRIMARY KEY (`cedula`),
  UNIQUE INDEX `cedula_UNIQUE` (`cedula` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cofinance`.`Categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cofinance`.`Categoria` ;

CREATE TABLE IF NOT EXISTS `cofinance`.`Categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cofinance`.`TiposCrowfunding`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cofinance`.`TiposCrowfunding` ;

CREATE TABLE IF NOT EXISTS `cofinance`.`TiposCrowfunding` (
  `idTiposCrowfunding` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idTiposCrowfunding`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cofinance`.`SubCategoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cofinance`.`SubCategoria` ;

CREATE TABLE IF NOT EXISTS `cofinance`.`SubCategoria` (
  `idSubCategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`idSubCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cofinance`.`Proyectos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cofinance`.`Proyectos` ;

CREATE TABLE IF NOT EXISTS `cofinance`.`Proyectos` (
  `idProyectos` INT NOT NULL AUTO_INCREMENT,
  `nombreProyecto` VARCHAR(150) NOT NULL,
  `descripcionProyecto` TEXT NOT NULL,
  `provinciaProyecto` VARCHAR(45) NOT NULL,
  `cuidadProyecto` VARCHAR(45) NOT NULL,
  `impactoSocial` TEXT NOT NULL,
  `montoSolicitado` DECIMAL(15,2) NOT NULL,
  `inicioPlazoProyecto` DATE NULL,
  `finPlazoProyecto` DATE NULL,
  `videoPresentacionProyecto` LONGBLOB NULL,
  `frecuenciaActualizaciones` ENUM('Mensual', 'Bimestre', 'Trimestre', 'Cuatrimestre', 'Semestre') NULL,
  `fechaCreacionProyecto` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `estado` ENUM('Pendiente', 'Aprobada', 'Rechazada') NOT NULL DEFAULT 'Pendiente',
  `Categoria_idCategoria` INT NOT NULL,
  `TiposCrowfunding_idTiposCrowfunding` INT NOT NULL,
  `SubCategoria_idSubCategoria` INT NOT NULL,
  PRIMARY KEY (`idProyectos`, `Categoria_idCategoria`, `TiposCrowfunding_idTiposCrowfunding`, `SubCategoria_idSubCategoria`),
  INDEX `fk_Proyectos_Categoria1_idx` (`Categoria_idCategoria` ASC) VISIBLE,
  INDEX `fk_Proyectos_TiposCrowfunding1_idx` (`TiposCrowfunding_idTiposCrowfunding` ASC) VISIBLE,
  INDEX `fk_Proyectos_SubCategoria1_idx` (`SubCategoria_idSubCategoria` ASC) VISIBLE,
  CONSTRAINT `fk_Proyectos_Categoria1`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `cofinance`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Proyectos_TiposCrowfunding1`
    FOREIGN KEY (`TiposCrowfunding_idTiposCrowfunding`)
    REFERENCES `cofinance`.`TiposCrowfunding` (`idTiposCrowfunding`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Proyectos_SubCategoria1`
    FOREIGN KEY (`SubCategoria_idSubCategoria`)
    REFERENCES `cofinance`.`SubCategoria` (`idSubCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cofinance`.`Validacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cofinance`.`Validacion` ;

CREATE TABLE IF NOT EXISTS `cofinance`.`Validacion` (
  `idValidaciones` INT NOT NULL AUTO_INCREMENT,
  `tipoValidacion` ENUM('Identidad', 'Financiera', 'Credibilidad') NOT NULL,
  `estadoValidacion` ENUM('Pendiente', 'Aprobada', 'Rechazada') NULL,
  `documentacionValRuta` VARCHAR(255) NULL,
  `fechaSolicitud` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `fechaValidacion` DATETIME NULL,
  `Proyectos_idProyectos` INT NOT NULL,
  PRIMARY KEY (`idValidaciones`, `Proyectos_idProyectos`),
  INDEX `fk_Validacion_Proyectos1_idx` (`Proyectos_idProyectos` ASC) VISIBLE,
  CONSTRAINT `fk_Validacion_Proyectos1`
    FOREIGN KEY (`Proyectos_idProyectos`)
    REFERENCES `cofinance`.`Proyectos` (`idProyectos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cofinance`.`Multimedia_Evidencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cofinance`.`Multimedia_Evidencia` ;

CREATE TABLE IF NOT EXISTS `cofinance`.`Multimedia_Evidencia` (
  `idMultimedia_Evidencia` INT NOT NULL AUTO_INCREMENT,
  `tituloEvidencia` VARCHAR(45) NULL,
  `fechaEvidencia` DATETIME NULL,
  `contenidoEvidenciaRuta` VARCHAR(255) NULL,
  `fechaSubida` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `Proyectos_idProyectos` INT NOT NULL,
  PRIMARY KEY (`idMultimedia_Evidencia`, `Proyectos_idProyectos`),
  INDEX `fk_Multimedia_Evidencia_Proyectos1_idx` (`Proyectos_idProyectos` ASC) VISIBLE,
  CONSTRAINT `fk_Multimedia_Evidencia_Proyectos1`
    FOREIGN KEY (`Proyectos_idProyectos`)
    REFERENCES `cofinance`.`Proyectos` (`idProyectos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cofinance`.`Prestatario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cofinance`.`Prestatario` ;

CREATE TABLE IF NOT EXISTS `cofinance`.`Prestatario` (
  `Usuario_cedula` VARCHAR(10) NOT NULL,
  `tipoOrganizacion` ENUM('Persona Individual', 'Organización Comunitaria', 'Empresa') NOT NULL,
  `descripcionPerfil` TEXT NOT NULL,
  `experienciaProyecto` JSON NULL,
  PRIMARY KEY (`Usuario_cedula`),
  INDEX `fk_Prestatario_Usuario1_idx` (`Usuario_cedula` ASC) VISIBLE,
  UNIQUE INDEX `Usuario_cedula_UNIQUE` (`Usuario_cedula` ASC) VISIBLE,
  CONSTRAINT `fk_Prestatario_Usuario1`
    FOREIGN KEY (`Usuario_cedula`)
    REFERENCES `cofinance`.`Usuario` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cofinance`.`Rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cofinance`.`Rol` ;

CREATE TABLE IF NOT EXISTS `cofinance`.`Rol` (
  `idRol` INT NOT NULL AUTO_INCREMENT,
  `nombreRol` VARCHAR(50) NULL,
  PRIMARY KEY (`idRol`),
  UNIQUE INDEX `idRol_UNIQUE` (`idRol` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cofinance`.`Prestamista`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cofinance`.`Prestamista` ;

CREATE TABLE IF NOT EXISTS `cofinance`.`Prestamista` (
  `Usuario_cedula` VARCHAR(10) NOT NULL,
  `nivelEstudio` VARCHAR(45) NOT NULL,
  `ocupacion` VARCHAR(100) NOT NULL,
  `ingresosMensuales` DECIMAL(12,2) NOT NULL,
  `preferenciaInversion` ENUM('Recompensa', 'Donación', 'Prestamo', 'Inversión') NOT NULL,
  `metodoPagoPreferido` ENUM('Transferencia Bancaria', 'Tarjeta de Crédito', 'Billetera Digital') NULL,
  PRIMARY KEY (`Usuario_cedula`),
  INDEX `fk_Prestamista_Usuario1_idx` (`Usuario_cedula` ASC) VISIBLE,
  UNIQUE INDEX `Usuario_cedula_UNIQUE` (`Usuario_cedula` ASC) VISIBLE,
  CONSTRAINT `fk_Prestamista_Usuario1`
    FOREIGN KEY (`Usuario_cedula`)
    REFERENCES `cofinance`.`Usuario` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cofinance`.`Informacion_Contacto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cofinance`.`Informacion_Contacto` ;

CREATE TABLE IF NOT EXISTS `cofinance`.`Informacion_Contacto` (
  `Usuario_cedula` VARCHAR(10) NOT NULL,
  `idRegistro_Personal` INT NOT NULL,
  `telefono` VARCHAR(13) NOT NULL,
  `provincia` VARCHAR(40) NOT NULL,
  `cuidad` VARCHAR(40) NOT NULL,
  `callePrincipal` VARCHAR(60) NULL,
  `calleSecundaria` VARCHAR(60) NULL,
  `codigoPostal` VARCHAR(6) NULL,
  `nroCasa` VARCHAR(7) NULL,
  PRIMARY KEY (`Usuario_cedula`, `idRegistro_Personal`),
  UNIQUE INDEX `idRegistro_Personal_UNIQUE` (`idRegistro_Personal` ASC) VISIBLE,
  INDEX `fk_Informacion_Contacto_Usuario1_idx` (`Usuario_cedula` ASC) VISIBLE,
  UNIQUE INDEX `Usuario_cedula_UNIQUE` (`Usuario_cedula` ASC) VISIBLE,
  CONSTRAINT `fk_Informacion_Contacto_Usuario1`
    FOREIGN KEY (`Usuario_cedula`)
    REFERENCES `cofinance`.`Usuario` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cofinance`.`Soporte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cofinance`.`Soporte` ;

CREATE TABLE IF NOT EXISTS `cofinance`.`Soporte` (
  `Usuario_cedula` VARCHAR(10) NOT NULL,
  `nivelAcceso` ENUM('Superadmin', 'Verificador', 'Gestor') NULL,
  `especialidad` VARCHAR(100) NULL,
  `turno` ENUM('Mañana', 'Tarde', 'Noche') NULL,
  `departamento` VARCHAR(45) NULL,
  `casosAtendidos` INT NULL,
  `fechaCreacion` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`Usuario_cedula`),
  INDEX `fk_Soporte_Usuario1_idx` (`Usuario_cedula` ASC) VISIBLE,
  UNIQUE INDEX `Usuario_cedula_UNIQUE` (`Usuario_cedula` ASC) VISIBLE,
  CONSTRAINT `fk_Soporte_Usuario1`
    FOREIGN KEY (`Usuario_cedula`)
    REFERENCES `cofinance`.`Usuario` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cofinance`.`Rol_has_Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cofinance`.`Rol_has_Usuario` ;

CREATE TABLE IF NOT EXISTS `cofinance`.`Rol_has_Usuario` (
  `Rol_idRol` INT NOT NULL,
  `Usuario_cedula` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Rol_idRol`, `Usuario_cedula`),
  INDEX `fk_Rol_has_Usuario_Usuario1_idx` (`Usuario_cedula` ASC) VISIBLE,
  INDEX `fk_Rol_has_Usuario_Rol1_idx` (`Rol_idRol` ASC) VISIBLE,
  CONSTRAINT `fk_Rol_has_Usuario_Rol1`
    FOREIGN KEY (`Rol_idRol`)
    REFERENCES `cofinance`.`Rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rol_has_Usuario_Usuario1`
    FOREIGN KEY (`Usuario_cedula`)
    REFERENCES `cofinance`.`Usuario` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cofinance`.`Administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cofinance`.`Administrador` ;

CREATE TABLE IF NOT EXISTS `cofinance`.`Administrador` (
  `Usuario_cedula` VARCHAR(10) NOT NULL,
  `nivelAcceso` ENUM('Superadmin', 'Verificador', 'Gestor') NULL,
  `areaSupervision` VARCHAR(100) NULL,
  PRIMARY KEY (`Usuario_cedula`),
  INDEX `fk_Administrador_Usuario1_idx` (`Usuario_cedula` ASC) VISIBLE,
  UNIQUE INDEX `Usuario_cedula_UNIQUE` (`Usuario_cedula` ASC) VISIBLE,
  CONSTRAINT `fk_Administrador_Usuario1`
    FOREIGN KEY (`Usuario_cedula`)
    REFERENCES `cofinance`.`Usuario` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cofinance`.`Prestatario_has_Proyectos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cofinance`.`Prestatario_has_Proyectos` ;

CREATE TABLE IF NOT EXISTS `cofinance`.`Prestatario_has_Proyectos` (
  `Prestatario_Usuario_cedula` VARCHAR(10) NOT NULL,
  `Proyectos_idProyectos` INT NOT NULL,
  PRIMARY KEY (`Prestatario_Usuario_cedula`, `Proyectos_idProyectos`),
  INDEX `fk_Prestatario_has_Proyectos_Proyectos1_idx` (`Proyectos_idProyectos` ASC) VISIBLE,
  INDEX `fk_Prestatario_has_Proyectos_Prestatario1_idx` (`Prestatario_Usuario_cedula` ASC) VISIBLE,
  CONSTRAINT `fk_Prestatario_has_Proyectos_Prestatario1`
    FOREIGN KEY (`Prestatario_Usuario_cedula`)
    REFERENCES `cofinance`.`Prestatario` (`Usuario_cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prestatario_has_Proyectos_Proyectos1`
    FOREIGN KEY (`Proyectos_idProyectos`)
    REFERENCES `cofinance`.`Proyectos` (`idProyectos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cofinance`.`Ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cofinance`.`Ticket` ;

CREATE TABLE IF NOT EXISTS `cofinance`.`Ticket` (
  `idTicket` INT NOT NULL AUTO_INCREMENT,
  `descripcion` TEXT NULL,
  `estadoTicket` ENUM('Abierto', 'Espera', 'Cerrado') NULL,
  `fechaCreacionTicket` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `fechaCierreTicket` DATETIME NULL,
  `Usuario_cedula` VARCHAR(10) NOT NULL,
  `Soporte_Usuario_cedula` VARCHAR(10) NULL,
  PRIMARY KEY (`idTicket`, `Usuario_cedula`),
  UNIQUE INDEX `idTicket_UNIQUE` (`idTicket` ASC) VISIBLE,
  INDEX `fk_Ticket_Usuario1_idx` (`Usuario_cedula` ASC) VISIBLE,
  INDEX `fk_Ticket_Soporte1_idx` (`Soporte_Usuario_cedula` ASC) VISIBLE,
  CONSTRAINT `fk_Ticket_Usuario1`
    FOREIGN KEY (`Usuario_cedula`)
    REFERENCES `cofinance`.`Usuario` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ticket_Soporte1`
    FOREIGN KEY (`Soporte_Usuario_cedula`)
    REFERENCES `cofinance`.`Soporte` (`Usuario_cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cofinance`.`Transcciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cofinance`.`Transcciones` ;

CREATE TABLE IF NOT EXISTS `cofinance`.`Transcciones` (
  `idTranscciones` INT NOT NULL AUTO_INCREMENT,
  `montoTransaccion` DECIMAL(15,2) NOT NULL,
  `fechaTransaccion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `metodoPago` ENUM('Transferencia Bancaria', 'Tarjeta de Crédito', 'Billetera Digital') NOT NULL,
  `Prestamista_Usuario_cedula` VARCHAR(10) NOT NULL,
  `Proyectos_idProyectos` INT NOT NULL,
  PRIMARY KEY (`idTranscciones`, `Prestamista_Usuario_cedula`, `Proyectos_idProyectos`),
  INDEX `fk_Transcciones_Prestamista1_idx` (`Prestamista_Usuario_cedula` ASC) VISIBLE,
  INDEX `fk_Transcciones_Proyectos1_idx` (`Proyectos_idProyectos` ASC) VISIBLE,
  CONSTRAINT `fk_Transcciones_Prestamista1`
    FOREIGN KEY (`Prestamista_Usuario_cedula`)
    REFERENCES `cofinance`.`Prestamista` (`Usuario_cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transcciones_Proyectos1`
    FOREIGN KEY (`Proyectos_idProyectos`)
    REFERENCES `cofinance`.`Proyectos` (`idProyectos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cofinance`.`Donaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cofinance`.`Donaciones` ;

CREATE TABLE IF NOT EXISTS `cofinance`.`Donaciones` (
  `idDonaciones` INT NOT NULL AUTO_INCREMENT,
  `montoDonacion` DECIMAL(15,2) NOT NULL,
  `metodoPago` ENUM('Transferencia Bancaria', 'Tarjeta de Crédito', 'Billetera Digital') NOT NULL,
  `fechaDonacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Prestamista_Usuario_cedula` VARCHAR(10) NOT NULL,
  `Proyectos_idProyectos` INT NOT NULL,
  PRIMARY KEY (`idDonaciones`, `Prestamista_Usuario_cedula`, `Proyectos_idProyectos`),
  INDEX `fk_Donaciones_Prestamista1_idx` (`Prestamista_Usuario_cedula` ASC) VISIBLE,
  INDEX `fk_Donaciones_Proyectos1_idx` (`Proyectos_idProyectos` ASC) VISIBLE,
  CONSTRAINT `fk_Donaciones_Prestamista1`
    FOREIGN KEY (`Prestamista_Usuario_cedula`)
    REFERENCES `cofinance`.`Prestamista` (`Usuario_cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Donaciones_Proyectos1`
    FOREIGN KEY (`Proyectos_idProyectos`)
    REFERENCES `cofinance`.`Proyectos` (`idProyectos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cofinance`.`Prestamos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cofinance`.`Prestamos` ;

CREATE TABLE IF NOT EXISTS `cofinance`.`Prestamos` (
  `idPrestamos` INT NOT NULL AUTO_INCREMENT,
  `montoPrestado` DECIMAL(15,2) NOT NULL,
  `tasaInteres` DECIMAL(5,2) NULL,
  `metodoPago` ENUM('Transferencia Bancaria', 'Tarjeta de Crédito', 'Billetera Digital') NOT NULL,
  `fechaPrestamo` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fechaVencimiento` DATETIME NULL,
  `Prestamista_Usuario_cedula` VARCHAR(10) NOT NULL,
  `Proyectos_idProyectos` INT NOT NULL,
  PRIMARY KEY (`idPrestamos`, `Prestamista_Usuario_cedula`, `Proyectos_idProyectos`),
  INDEX `fk_Prestamos_Prestamista1_idx` (`Prestamista_Usuario_cedula` ASC) VISIBLE,
  INDEX `fk_Prestamos_Proyectos1_idx` (`Proyectos_idProyectos` ASC) VISIBLE,
  CONSTRAINT `fk_Prestamos_Prestamista1`
    FOREIGN KEY (`Prestamista_Usuario_cedula`)
    REFERENCES `cofinance`.`Prestamista` (`Usuario_cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prestamos_Proyectos1`
    FOREIGN KEY (`Proyectos_idProyectos`)
    REFERENCES `cofinance`.`Proyectos` (`idProyectos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cofinance`.`InversionAcciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cofinance`.`InversionAcciones` ;

CREATE TABLE IF NOT EXISTS `cofinance`.`InversionAcciones` (
  `idInversionAcciones` INT NOT NULL AUTO_INCREMENT,
  `montoInvertido` DECIMAL(15,2) NOT NULL,
  `porcentajeAcciones` DECIMAL(5,2) NOT NULL,
  `metodoPago` ENUM('Transferencia Bancaria', 'Tarjeta de Crédito', 'Billetera Digital') NOT NULL,
  `fechaInversion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Prestamista_Usuario_cedula` VARCHAR(10) NOT NULL,
  `Proyectos_idProyectos` INT NOT NULL,
  PRIMARY KEY (`idInversionAcciones`, `Prestamista_Usuario_cedula`, `Proyectos_idProyectos`),
  INDEX `fk_InversionAcciones_Prestamista1_idx` (`Prestamista_Usuario_cedula` ASC) VISIBLE,
  INDEX `fk_InversionAcciones_Proyectos1_idx` (`Proyectos_idProyectos` ASC) VISIBLE,
  CONSTRAINT `fk_InversionAcciones_Prestamista1`
    FOREIGN KEY (`Prestamista_Usuario_cedula`)
    REFERENCES `cofinance`.`Prestamista` (`Usuario_cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_InversionAcciones_Proyectos1`
    FOREIGN KEY (`Proyectos_idProyectos`)
    REFERENCES `cofinance`.`Proyectos` (`idProyectos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cofinance`.`Recompensas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cofinance`.`Recompensas` ;

CREATE TABLE IF NOT EXISTS `cofinance`.`Recompensas` (
  `idRecompensas` INT NOT NULL AUTO_INCREMENT,
  `decripcion` TEXT NULL,
  `montoMinimo` DECIMAL(15,2) NULL,
  `cantidadDisponible` INT NULL,
  `fechaCreacionRecom` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `Proyectos_idProyectos` INT NOT NULL,
  PRIMARY KEY (`idRecompensas`, `Proyectos_idProyectos`),
  INDEX `fk_Recompensas_Proyectos1_idx` (`Proyectos_idProyectos` ASC) VISIBLE,
  CONSTRAINT `fk_Recompensas_Proyectos1`
    FOREIGN KEY (`Proyectos_idProyectos`)
    REFERENCES `cofinance`.`Proyectos` (`idProyectos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cofinance`.`Transcciones_has_Recompensas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cofinance`.`Transcciones_has_Recompensas` ;

CREATE TABLE IF NOT EXISTS `cofinance`.`Transcciones_has_Recompensas` (
  `Transcciones_idTranscciones` INT NOT NULL,
  `Recompensas_idRecompensas` INT NOT NULL,
  `cantidad` INT NULL,
  PRIMARY KEY (`Transcciones_idTranscciones`, `Recompensas_idRecompensas`),
  INDEX `fk_Transcciones_has_Recompensas_Recompensas1_idx` (`Recompensas_idRecompensas` ASC) VISIBLE,
  INDEX `fk_Transcciones_has_Recompensas_Transcciones1_idx` (`Transcciones_idTranscciones` ASC) VISIBLE,
  CONSTRAINT `fk_Transcciones_has_Recompensas_Transcciones1`
    FOREIGN KEY (`Transcciones_idTranscciones`)
    REFERENCES `cofinance`.`Transcciones` (`idTranscciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transcciones_has_Recompensas_Recompensas1`
    FOREIGN KEY (`Recompensas_idRecompensas`)
    REFERENCES `cofinance`.`Recompensas` (`idRecompensas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cofinance`.`VerificionesUsuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cofinance`.`VerificionesUsuario` ;

CREATE TABLE IF NOT EXISTS `cofinance`.`VerificionesUsuario` (
  `idVerificionesUsuario` INT NOT NULL AUTO_INCREMENT,
  `tipoVerificacion` ENUM('Identidad', 'Financiera', 'Credibilidad') NULL,
  `estadoVerifiacio` ENUM('Pendiente', 'Aprovada', 'Rechazada') NOT NULL DEFAULT 'Pendiente',
  `fechaSolicitud` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fechaVerificacionUsu` DATETIME NULL,
  `documentoRutaVU` VARCHAR(255) NULL,
  `comentarios` TEXT NULL,
  `Usuario_cedula` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idVerificionesUsuario`, `Usuario_cedula`),
  INDEX `fk_VerificionesUsuario_Usuario1_idx` (`Usuario_cedula` ASC) VISIBLE,
  CONSTRAINT `fk_VerificionesUsuario_Usuario1`
    FOREIGN KEY (`Usuario_cedula`)
    REFERENCES `cofinance`.`Usuario` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
